---
title: "Section 1.1"
author: "johan jordaan"
output: html_notebook
---

1. Analyse the logic forms of the following statements:

    a.  We'll have either a reading assignment or homework problems, but we won't have both homework problems and a test.
    
    ***
    
      Let :
      + $A =$ a reading assignment
      + $B =$ homework problems
      + $C =$ a test
      
      In :
      + We'll have either **a reading assignment** or **homework problems**, but we won't have both **homework problems** and **a test**.
  
  
      Then :
      + We'll have either $A$ or $B$, but we won't have both $A$ and $C$
      + We'll have either $A \vee B$, but we $\neg$ $(A \wedge C)$
      
      And  finally :
      + $(A \vee B) \wedge \neg (A \wedge C)$
    
    ***
    
    b. You won't go skiing, or you will and there won't be any snow

    ***
    
    Let :
    + $A =$ go skiing 
    + $B =$ there will be snow
    
    In :
    + You won't **go skiing**, or you will and there won't **be any snow**    

    Then :
    + You won't $A$, or you will and won't $B$
    + You $\neg A$, or $A$ and $\neg B$
    
    And finally :
    + $\neg A \vee (A \wedge \neg B)$


    ***
    
    c. $\sqrt{7} \le 2$.

    ***
    
    Let :
    + $A \le B => A < B \vee A = B$

    Then :
    + $\sqrt{7} \le 2 => \sqrt{7} < 2 \vee \sqrt{7} = 2$


    ***


2. Analyse the logic forms of the following statements:

    a. Either John and Bill are both telling the truth, or neither of them is.

    ***
    
    Let :
    + $J =$ John is telling the truth 
    + $B =$ Bill is telling the truth
    
    In :
    + Either **John is telling the truth** and **Bill is telling the truth**, or neither of then is.
    
    Then :
    + Either $J$ and $B$, or neither of then is
    + Either $J \wedge B$, or neither $J \wedge B$
    + Either $J \wedge B$, or  $\neg(J \wedge B)$
    
    And finally:
    + $(J \wedge B) \vee \neg(J \wedge B)$
  

    ***

    b. I'll have either fish or chicken, but I won't have both fish and mashed potatoes.

    ***
    
    Let :
    + $F =$ I'll have fish 
    + $C =$ I'll have chicken
    + $M =$ I'll have masked potatoes
    
    Then :
    + $F \vee C$, but I won't have $F \wedge M$
    + $F \vee C$ , but $\neg $F \wedge M$
    
    And fibally:
    + $(F \vee C) \wedge \neg (F \wedge M)$
    

    ***
    
    c. 3 is a common divisor of 6,9 and 15

    ***
    
    
    
    ***

    
3. Analyse the logic forms of the following statements:

    a. Alice and Bob are not both in the room.

    ***
    

    ***

    b. Alice and Bob are both not in the room.

    ***
    

    ***

    c. Either Alice or Bob is not in the room.

    ***
    

    ***


    d. Neither Alice nor Bob is in the room.

    ***
    

    ***

